spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/clother
    username: clotheruser
    password: clotheruser

#server:
#  servlet:
#    context-path: /




logging:
  level:
    root: info  # 전체 기본 로그 레벨
    com:
      microsoftwo:
        clother:
          adviceBoard:
            query: debug
            command: debug



